apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogMW0KICBzbGFja19hcGlfdXJsOiAnaHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAyUzROWDNONlEvQjAzMEEyWlJYSzkvWVRvdWFmOTNLaDhtSkN5ajQ4VElOV3huJwpyb3V0ZToKICByZWNlaXZlcjogJ3NsYWNrLW5vdGlmaWNhdGlvbnMnICAKICByb3V0ZXM6CiAgLSBtYXRjaDoKICAgICAgc2V2ZXJpdHk6IHdhcm5pbmcKcmVjZWl2ZXJzOgotIG5hbWU6ICdzbGFjay1ub3RpZmljYXRpb25zJwogIHNsYWNrX2NvbmZpZ3M6CiAgLSBjaGFubmVsOiAnI2FsZXJ0LXByb21ldGhldXMnCiAgICB0ZXh0OiAiUHJ1ZWJhcyBkZSByZXBldGljacOzbiAxIgogICAgc2VuZF9yZXNvbHZlZDogdHJ1ZQ==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: guane
    meta.helm.sh/release-namespace: prometheus
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: guane
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 30.2.0
    chart: kube-prometheus-stack-30.2.0
    heritage: Helm
    release: guane
  name: alertmanager-guane-kube-prometheus-stac-alertmanager
  namespace: prometheus
type: Opaque
